spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FoodOrderService?useSSL=false&allowPublicKeyRetrieval=true
    drvierClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Safeheaven97$
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
 
eureka:
  instance:
      preferIpAddress: true
  client:
    register-with-client: true
    fetch-registry: true
    service-url: 
      defaultZone: http://bmt-registry:8761/eureka/
