spring:
  datasource:
    url: jdbc:mysql://mysql:3306/FoodOrderService
    drvierClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
 
eureka:
  instance:
      preferIpAddress: true
  client:
    register-with-client: true
    fetch-registry: true
    service-url: 
      defaultZone: http://bmt-registry:8761/eureka/