spring:
  datasource:
    url: jdbc:mysql://mysql:3306/FoodOrderService
    drvierClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect